In [1]:
%reload_ext autoreload
%autoreload 2

In [5]:
from transformations.text.contraction.expand_contractions import ExpandContractions
from transformations.text.contraction.contract_contractions import ContractContractions
from transformations.text.emoji.emojify import Emojify, AddPositiveEmoji, AddNegativeEmoji, AddNeutralEmoji
from transformations.text.emoji.demojify import Demojify, RemovePositiveEmoji, RemoveNegativeEmoji, RemoveNeutralEmoji
from transformations.text.negation.remove_negation import RemoveNegation
from transformations.text.negation.add_negation import AddNegation
from transformations.text.contraction.expand_contractions import ExpandContractions
from transformations.text.contraction.contract_contractions import ContractContractions
from transformations.text.word_swap.change_number import ChangeNumber
from transformations.text.word_swap.change_synse import ChangeSynonym, ChangeAntonym, ChangeHyponym, ChangeHypernym
from transformations.text.word_swap.word_deletion import WordDeletion
from transformations.text.word_swap.homoglyph_swap import HomoglyphSwap
from transformations.text.word_swap.random_swap import RandomSwap
from transformations.text.insertion.random_insertion import RandomInsertion
from transformations.text.insertion.sentiment_phrase import InsertSentimentPhrase, InsertPositivePhrase, InsertNegativePhrase
from transformations.text.links.add_sentiment_link import AddSentimentLink, AddPositiveLink, AddNegativeLink
from transformations.text.links.import_link_text import ImportLinkText
from transformations.text.entities.change_location import ChangeLocation
from transformations.text.entities.change_name import ChangeName
from transformations.text.typos.char_delete import RandomCharDel
from transformations.text.typos.char_insert import RandomCharInsert
from transformations.text.typos.char_substitute import RandomCharSubst
from transformations.text.typos.char_swap import RandomCharSwap
from transformations.text.typos.char_swap_qwerty import RandomSwapQwerty
from transformations.text.mixture.text_mix import TextMix, SentMix, WordMix

In [6]:
from datasets import load_dataset
from collections import defaultdict
import pandas as pd
import random
import time

### Data

In [7]:
dataset = load_dataset("ag_news")

Using custom data configuration default
Reusing dataset ag_news (C:\Users\fabri\.cache\huggingface\datasets\ag_news\default\0.0.0\fb5c5e74a110037311ef5e904583ce9f8b9fbc1354290f97b4929f01b3f48b1a)


### Transformation

In [9]:
transformations = [
    ExpandContractions,
    ContractContractions,
    Emojify,
    AddPositiveEmoji,
    AddNegativeEmoji,
    AddNeutralEmoji,
    Demojify, 
    RemovePositiveEmoji,
    RemoveNegativeEmoji,
    RemoveNeutralEmoji,
    ChangeLocation,
    ChangeName,
    InsertPositivePhrase,
    InsertNegativePhrase,
    RandomInsertion,
    AddPositiveLink,
    AddNegativeLink,
    ImportLinkText,
    AddNegation,
    RemoveNegation,
    RandomCharDel,
    RandomCharInsert, 
    RandomCharSubst, 
    RandomCharSwap, 
    RandomSwapQwerty,
    ChangeNumber,
    ChangeSynonym, 
    ChangeAntonym, 
    ChangeHyponym, 
    ChangeHypernym,
    WordDeletion, 
    HomoglyphSwap, 
    RandomSwap,
    TextMix,
    SentMix,
    WordMix
]

In [10]:
df_all = []
for transform in transformations:
    t = transform()
    df = t.get_tran_types()
    df['transformation'] = t.__class__.__name__
    df['tran_fn'] = t
    df_all.append(df)
    
df = pd.concat(df_all)

### INV Transforms

In [305]:
task = df['task_name'] == 'topic'
tran = df['tran_type'] == 'INV'

df_all = df[task & tran]
df_all

task_name tran_type        transformation  \
1     topic       INV    ExpandContractions   
1     topic       INV  ContractContractions   
1     topic       INV               Emojify   
1     topic       INV      AddPositiveEmoji   
1     topic       INV      AddNegativeEmoji   
1     topic       INV       AddNeutralEmoji   
1     topic       INV              Demojify   
1     topic       INV   RemovePositiveEmoji   
1     topic       INV   RemoveNegativeEmoji   
1     topic       INV    RemoveNeutralEmoji   
1     topic       INV        ChangeLocation   
1     topic       INV            ChangeName   
1     topic       INV  InsertPositivePhrase   
1     topic       INV  InsertNegativePhrase   
1     topic       INV       RandomInsertion   
1     topic       INV       AddPositiveLink   
1     topic       INV       AddNegativeLink   
1     topic       INV        ImportLinkText   
1     topic       INV           AddNegation   
1     topic       INV        RemoveNegation   
1     topic       INV         RandomCharDel   
1     topic       INV      RandomCharInsert   
1     topic       INV       RandomCharSubst   
1     topic       INV        RandomCharSwap   
1     topic       INV      RandomSwapQwerty   
1     topic       INV          ChangeNumber   
1     topic       INV         ChangeSynonym   
1     topic       INV         ChangeAntonym   
1     topic       INV         ChangeHyponym   
1     topic       INV        ChangeHypernym   
1     topic       INV          WordDeletion   
1     topic       INV         HomoglyphSwap   
1     topic       INV            RandomSwap   

                                             tran_fn  
1  <transformations.text.contraction.expand_contr...  
1  <transformations.text.contraction.contract_con...  
1  <transformations.text.emoji.emojify.Emojify ob...  
1  <transformations.text.emoji.emojify.AddPositiv...  
1  <transformations.text.emoji.emojify.AddNegativ...  
1  <transformations.text.emoji.emojify.AddNeutral...  
1  <transformations.text.emoji.demojify.Demojify ...  
1  <transformations.text.emoji.demojify.RemovePos...  
1  <transformations.text.emoji.demojify.RemoveNeg...  
1  <transformations.text.emoji.demojify.RemoveNeu...  
1  <transformations.text.entities.change_location...  
1  <transformations.text.entities.change_name.Cha...  
1  <transformations.text.insertion.sentiment_phra...  
1  <transformations.text.insertion.sentiment_phra...  
1  <transformations.text.insertion.random_inserti...  
1  <transformations.text.links.add_sentiment_link...  
1  <transformations.text.links.add_sentiment_link...  
1  <transformations.text.links.import_link_text.I...  
1  <transformations.text.negation.add_negation.Ad...  
1  <transformations.text.negation.remove_negation...  
1  <transformations.text.typos.char_delete.Random...  
1  <transformations.text.typos.char_insert.Random...  
1  <transformations.text.typos.char_substitute.Ra...  
1  <transformations.text.typos.char_swap.RandomCh...  
1  <transformations.text.typos.char_swap_qwerty.R...  
1  <transformations.text.word_swap.change_number....  
1  <transformations.text.word_swap.change_synse.C...  
1  <transformations.text.word_swap.change_synse.C...  
1  <transformations.text.word_swap.change_synse.C...  
1  <transformations.text.word_swap.change_synse.C...  
1  <transformations.text.word_swap.word_deletion....  
1  <transformations.text.word_swap.homoglyph_swap...  
1  <transformations.text.word_swap.random_swap.Ra...

In [12]:
n = 20
i = random.randint(0, len(dataset['train']['text']) - 1 - n)
X, y = dataset['train']['text'][i:i+n], dataset['train']['label'][i:i+n]

In [13]:
Xs, ys, ts = X, y, defaultdict(list)
num_X = 1000

tic = time.perf_counter()
while len(Xs) < num_X:
    
    # sample an (X,y) pair
    i = random.randint(0, len(Xs) - 1)
    X_, y_, ts_ = Xs[i], ys[i], ts[i]
    
    # sample a transformation
    t_df   = df_all.sample(1)
    t_fn   = t_df['tran_fn'][0]
    t_name = t_df['transformation'][0]
                
    if t_name in ts_:
        continue
    
    applied_ts = ts_ + [t_name]

    new_X_, new_y_ = t_fn.transform_Xy(X_, y_)

    if new_X_ not in Xs:
        Xs.append(new_X_)
        ys.append(new_y_)
        j = len(Xs) - 1
        ts[j].extend(applied_ts)
    
toc = time.perf_counter()
print('Time to generate {0} examples: {1:.2f} seconds'.format(num_X, (toc - tic)))

Time to generate 1000 examples: 35.48 seconds


In [17]:
len(Xs), len(ys)

(1000, 1000)

In [14]:
ts

defaultdict(list,
            {3: [],
             20: ['ContractContractions'],
             7: [],
             21: ['RandomCharDel'],
             13: [],
             17: [],
             22: ['HomoglyphSwap'],
             2: [],
             23: ['RandomSwap'],
             6: [],
             24: ['ChangeHyponym'],
             0: [],
             25: ['AddNeutralEmoji'],
             18: [],
             26: ['ContractContractions'],
             1: [],
             27: ['ChangeHypernym'],
             28: ['ContractContractions', 'WordDeletion'],
             10: [],
             29: ['RandomSwapQwerty'],
             30: ['ChangeHypernym', 'RandomCharSubst'],
             14: [],
             31: ['RandomCharInsert'],
             32: ['RandomCharSubst'],
             8: [],
             33: ['RandomSwap'],
             34: ['AddNeutralEmoji', 'RandomCharSubst'],
             35: ['Emojify'],
             36: ['RandomSwap', 'HomoglyphSwap'],
             37: ['RandomSwap', 'C

### SIB Transforms

In [11]:
task = df['task_name'] == 'topic'
tran = df['tran_type'] == 'SIB'

df_all = df[task & tran]
df_all

task_name tran_type transformation  \
1     topic       SIB        TextMix   
1     topic       SIB        SentMix   
1     topic       SIB        WordMix   

                                             tran_fn  
1  <transformations.text.mixture.text_mix.TextMix...  
1  <transformations.text.mixture.text_mix.SentMix...  
1  <transformations.text.mixture.text_mix.WordMix...

In [12]:
n = 100
i = random.randint(0, len(dataset['train']['text']) - 1 - n)
X, y = np.array(dataset['train']['text'][i:i+n], dtype=np.string_), np.array(dataset['train']['label'][i:i+n])
batch = (X, y)

In [13]:
ts = df_all['tran_fn'].tolist()

datasets = {}
tic = time.perf_counter()
for t in ts:
    t_name = t.__class__.__name__
    print(t_name)
    (data, targets) = t(batch)
    datasets[t_name] = {
        'data' : data,
        'targets' : targets
    }

toc = time.perf_counter()
print('Time to generate {0} examples: {1:.2f} seconds'.format(len(batch[0]), (toc - tic)))

TextMix
SentMix
WordMix
Time to generate 100 examples: 0.06 seconds


In [16]:
for X, y in zip(datasets["TextMix"]['data'], datasets["TextMix"]['targets']):
    print(X)
    print(y)

b"A Favorite Emerges A company with close ties to White Sox owner Jerry Reinsdorf is a leading candidate for a contract to help plan Washington's new stadium. Black Caps duo cleared to play Australia BRISBANE: Brendon McCullum and Scott Styris were last night forgiven for expressing pent-up frustration at the Sydney Cricket Ground on Wednesday night and cleared to play the Chappell-Hadlee "
[0. 1. 0. 0.]
b'Food running so low aboard station that crew ordered to cut back &lt;b&gt;...&lt;/b&gt; Food is running so low aboard the international space station that flight controllers have instructed the two crewmen to cut back on calories, at least until a Russian supply ship arrives in a little over two weeks. Summary: Bush Has Full Agenda for January (AP) AP - FIRST ON TAP: President Bush was meeting Monday with nine new senators and 41 new representatives joining the 109th Congress in a session that a spokesman said was aimed at "coming together."'
[0.44505495 0.         0.         0.55494

In [17]:
for X, y in zip(datasets["SentMix"]['data'], datasets["SentMix"]['targets']):
    print(X)
    print(y)

b"A Favorite Emerges A company with close ties to White Sox owner Jerry Reinsdorf is a leading candidate for a contract to help plan Washington's new stadium. Most Browsers Vulnerable to Pop-Up Attack Five advisories issued by security firm Secunia warn that a pop-up attack could expose users to phishing scams on most Web browsers."
[0.         0.47272727 0.         0.52727273]
b'Food running so low aboard station that crew ordered to cut back &lt;b&gt;...&lt;/b&gt; Food is running so low aboard the international space station that flight controllers have instructed the two crewmen to cut back on calories, at least until a Russian supply ship arrives in a little over two weeks. Holmes hurt knee against the Bucs The Kansas City Chiefs put running back Priest Holmes on the injured reserve list with an injured knee Thursday. quot;Priest Holmes is making steady progress on the rehabilitation of his right knee, quot; team president Carl Peterson said.'
[0.         0.47487002 0.         0.52

In [18]:
for X, y in zip(datasets["WordMix"]['data'], datasets["WordMix"]['targets']):
    print(X)
    print(y)

that Glaus b"A contract message of sends the them." contending they company been with a Arizona ties Favorite team Diamondbacks saying a in in Jerry just for help recent to with Sox field is a hope owner It White 2005. #39;s leading months to to Reinsdorf little close new kept stewards Washington's a hear hard intend The signing stadium. A candidate plan a to of Emerges
[0. 1. 0. 0.]
frozen running have hints arrives new aboard Food solar ship Russian body at suggest ordered to on a flight back so low least heavenly b'Food calories, international full not a that cemetery that a space two system dead, cut object outer station of station cut &lt;b&gt;...&lt;/b&gt; so Quaoar.' warm two little bodies, aboard in be a of may is weeks. the to back the a over large observations low heart until supply The controllers called instructed running crewmen crew at Frozen
[0. 0. 0. 1.]
SKG maker, Dip quot;Shrek build of Dutch network quot; leading Technologies, #39;Shrek back wins Telfort, b'Huawei Ho